{
	"label_totalProductionToday"		: "TOTAL PRODUCTION TODAY",
	"label_totalProductionYesterday"	: "Yesterday",
	"label_totalProductionPreviousYear"	: "Previous year",
	"label_totalPowerRightNow"			: "TOTAL POWER RIGHT NOW",
	"label_maximumProduction"			: "Max possible production",
	"label_thisWillPower"				: "Current production can supply",
	"label_windspeed"					: "WIND SPEED<br/>TOP 3 RIGHT NOW",
	"label_active"						: "ACTIVE POWER<br/>TOP 3 RIGHT NOW",
	"label_availability"				: "AVAILABILITY<br/>TOP 3 RIGHT NOW",
	"label_windspeedSmall"				: "WIND SPEED TOP 3 RIGHT NOW",
	"label_activeSmall"					: "ACTIVE POWER TOP 3 RIGHT NOW",
	"label_availabilitySmall"			: "AVAILABILITY TOP 3 RIGHT NOW",
	"label_units"						: "Households",
	"label_updated"						: "Updated",
	"label_updating"					: "Updating...",
	"label_currencyEur"					: "EUR",
	"label_norway"						: "Norway",
	"label_sweden"						: "Sweden",
	"label_ukOnshore"					: "UK Onshore",
	"label_ukOffshore"					: "UK Offshore",
	"label_no"							: "NO",
	"label_se"							: "SE",
	"label_uk"							: "UK",
	"label_marketValue"					: "1 MWh WINDPOWER IS WORTH",
	"label_mwh"							: "MWh"
}